### ISSUE TITLE
Failed to find the account within the internal database

### ISSUE THREAD

**Issue by Analect** [loft-sh/devpod-provider-civo#3] opened 2024-04-06 20:50 UTC
I was experimenting to get this working, per this [blog](https://www.civo.com/learn/level-up-development-devpod).
I added the Civo provider (requiring you to supply a REGION and API_KEY), which seemed to work.

However, I'm getting this when I try to add a workspace. Any thoughts?

![image](https://github.com/loft-sh/devpod-provider-civo/assets/4063815/2a578dd9-d49d-403d-af35-817b213786b2)

Also, I notice that GPU-type instances from Civo are not exposed in this tool. I'm wondering if that can be rectified. Is this maintained by Loft or the Civo folks?

Thanks.

**Comment by 89luca89** [comment] 2024-04-09 08:01
Hi @Analect thanks for reporting!

I've just tried with a fresh install (both of devpod and civo provider) and I could not reproduce:
![image](https://github.com/loft-sh/devpod-provider-civo/assets/598882/9bf64af5-02fc-4acf-af75-673aacfc67bf)

Maybe this is related to the civo account?

**Comment by Analect** [comment] 2024-04-09 13:24
@89luca89 thanks. It seemed I needed to regenerate a new API key to get this to work. I'm interested in experimenting to see if I can run up a GPU instance type with `devpod`. A user needs to get specific quota to use these. Is there a way to pass an over-riding instance type based on the current provider, or would it need modification?

If you navigate to https://www.civo.com/api/sizes while logged in to civo, you can run `curl -H "Authorization: bearer xxxx" https://api.civo.com/v2/sizes` to get back instance-type names. I have a pending query into civo to determine why the GPU instances are not exposed here.

It seems from this [blog](https://www.civo.com/docs/compute/gpu-instance-drivers-ubuntu), if one is indeed able to launch a GPU instance via `devpod`, then various steps to install nvidia drivers are necessary too, possibly requiring an instance reboot. Is `devpod` able to handle that workflow, allowing for the fact that it may only be required the first time a VM is setup?

The other complicating factor here is that I think civo are operating a per-hour (rather than per-minute) pricing model, so any idle-sleep settings will have to account for that. I will clarify that with them.

![image](https://github.com/loft-sh/devpod-provider-civo/assets/4063815/25e2a58d-69ee-4930-a1f5-3e130933041b)

**Comment by 89luca89** [comment] 2024-04-10 07:34
> If you navigate to https://www.civo.com/api/sizes while logged in to civo, you can run curl -H "Authorization: bearer xxxx" https://api.civo.com/v2/sizes to get back instance-type names. I have a pending query into civo to determine why the GPU instances are not exposed here.

Instances are static list (the instance type) in the provider's manifest, so querying them is not an option
I'd say we'll just add all instances and let the API handle the error 

> It seems from this [blog](https://www.civo.com/docs/compute/gpu-instance-drivers-ubuntu), if one is indeed able to launch a GPU instance via devpod, then various steps to install nvidia drivers are necessary too, possibly requiring an instance reboot. Is devpod able to handle that workflow, allowing for the fact that it may only be required the first time a VM is setup?

This is out of scope from devpod, but what we can do is expose the `initialization script` field that CIVO also exposes, so that one can use the docs to set up things

Said that, these are lower priority feature for us at the moment, so it may take some times to see them implemented

If anyone is interested in contributing they are welcome! :smile:

**Closed as not planned** 2024-04-17 19:00 UTC
